% gen_srm_lut.m
% 功能：生成 Verilog 可用的 erf_inv 查找表
% 对应论文公式 (4.13)

clear; clc;

% --- 配置参数 ---
LUT_DEPTH = 256;       % SRM 计数器深度 (8-bit)
OUTPUT_WIDTH = 8;      % LUT 输出位宽
NOISE_SIGMA_LSB = 0.5; % 假设噪声标准差为 0.5 LSB (需根据实际模拟前端调整)
FILENAME = 'erf_inv_lut.vh';

% --- 计算 ---
% 输入 x 代表 SRM 统计到的 '1' 的个数 (0 到 255)
x = 0 : (LUT_DEPTH - 1);
P = x / (LUT_DEPTH - 1); % 概率 P

% 防止无穷大 (erfinv(1) = inf)
P(P > 0.999) = 0.999;
P(P < 0.001) = 0.001;

% 核心公式: V_res = sqrt(2) * sigma * erfinv(2P - 1)
% 这里我们归一化输出，让 FPGA 里的定点数处理更简单
v_res_float = sqrt(2) * NOISE_SIGMA_LSB * erfinv(2 * P - 1);

% 量化为有符号整数 (8-bit signed: -128 to 127)
scale_factor = (2^(OUTPUT_WIDTH-1) - 1) / max(abs(v_res_float)); 
lut_fixed = round(v_res_float * scale_factor);

% --- 生成 Verilog 头文件 ---
fid = fopen(FILENAME, 'w');
fprintf(fid, '// Auto-generated by MATLAB script gen_srm_lut.m\n');
fprintf(fid, '// Sigma: %.2f LSB, Scale: %.2f\n', NOISE_SIGMA_LSB, scale_factor);
fprintf(fid, 'logic signed [%d:0] erf_lut [0:%d] = ''{\n', OUTPUT_WIDTH-1, LUT_DEPTH-1);

for i = 1 : LUT_DEPTH
    if i == LUT_DEPTH
        fprintf(fid, '  %d\n', lut_fixed(i));
    else
        fprintf(fid, '  %d,\n', lut_fixed(i));
    end
end
fprintf(fid, '};\n');
fclose(fid);

disp(['成功生成 ', FILENAME, '，请将其放入 Vivado 工程目录。']);