"""Run a mismatch-only, noiseless normal-conversion validation campaign.

The experiment deliberately disables every normal-conversion noise source and
does not inject SRM residue into the decoded result.  All decoders see exactly
the same raw decisions generated by the mismatched physical weights.  The only
variable is the digital reconstruction weight set.

This isolates the question:

    Can the local foreground calibration remove static CDAC weight mismatch?

The converter remains the repository's current abstract 20-decision model. It
does not add the paper's split-sampling/VCM/AZ/2-bit-flash front-end sequence.
"""

from __future__ import annotations

import argparse
import csv
import json
import os
from concurrent.futures import ProcessPoolExecutor, as_completed
from dataclasses import asdict, replace
from pathlib import Path
from typing import Dict, Iterable, List, Tuple

import matplotlib.pyplot as plt
import numpy as np

from analysis.full_sar_behavioral_20260729.full_sar_model import (
    FullSarConfig,
    coherent_sine,
    full_scale_ramp,
    ideal_weight_q8,
    linearity_metrics,
    manufacture_chip_q8,
    rtl_reconstruct,
    run_normal_sar_conversion,
    run_rtl_equivalent_calibration,
    spectrum_metrics,
)


ROOT = Path(__file__).resolve().parent
DEFAULT_OUTDIR = ROOT / "outputs"
DECODERS = (
    "NOMINAL",
    "CAL_CURRENT_MEAS",
    "CAL_NOISELESS_MEAS",
    "ORACLE",
)


def noiseless_config(n_chips: int) -> FullSarConfig:
    """Return the qualified mismatch-only normal-conversion configuration."""

    return replace(
        FullSarConfig(n_chips=n_chips),
        sampling_noise_lsb=0.0,
        normal_comparator_noise_lsb=0.0,
        normal_comparator_offset_lsb=0.0,
        reference_noise_rms_fraction=0.0,
        dac_settling_error_fraction=0.0,
        srm_comparator_offset_lsb=0.0,
    )


def _affine_error(reference: np.ndarray, estimate: np.ndarray) -> Tuple[float, float, float, float]:
    """Return raw and affine-aligned code error relative to a reference."""

    ref = np.asarray(reference, dtype=float)
    est = np.asarray(estimate, dtype=float)
    raw_error = est - ref
    design = np.column_stack((est, np.ones_like(est)))
    gain, offset = np.linalg.lstsq(design, ref, rcond=None)[0]
    aligned_error = gain * est + offset - ref
    return (
        float(np.sqrt(np.mean(raw_error**2))),
        float(np.sqrt(np.mean(aligned_error**2))),
        float(np.max(np.abs(aligned_error))),
        float(gain),
    )


def _weight_error(reference_q8: np.ndarray, estimate_q8: np.ndarray, frac_bits: int) -> Tuple[float, float]:
    """Return gain-aligned weight RMSE and maximum error in final-code LSB."""

    reference = np.asarray(reference_q8, dtype=float)
    estimate = np.asarray(estimate_q8, dtype=float)
    denominator = float(np.dot(estimate, estimate))
    gain = float(np.dot(reference, estimate) / denominator) if denominator > 0.0 else 1.0
    error_lsb = (gain * estimate - reference) / float(1 << frac_bits)
    return float(np.sqrt(np.mean(error_lsb**2))), float(np.max(np.abs(error_lsb)))


def evaluate_chip(chip_id: int, cfg: FullSarConfig) -> List[Dict[str, object]]:
    """Evaluate one deterministic mismatch realization without conversion noise."""

    physical_q8 = manufacture_chip_q8(cfg, chip_id)
    calibrated_current_q8, _ = run_rtl_equivalent_calibration(physical_q8, cfg, chip_id)
    calibration_ideal_cfg = replace(
        cfg,
        calibration_comparator_offset_lsb=0.0,
        calibration_comparator_noise_lsb=0.0,
    )
    calibrated_noiseless_q8, _ = run_rtl_equivalent_calibration(
        physical_q8,
        calibration_ideal_cfg,
        chip_id,
    )

    sine_input, _, _ = coherent_sine(cfg, chip_id)
    ramp_input = full_scale_ramp(cfg)
    sine_conversion = run_normal_sar_conversion(
        sine_input,
        physical_q8,
        cfg,
        chip_id,
        stream_id=7101,
        include_random_noise=False,
        stochastic_srm=False,
    )
    ramp_conversion = run_normal_sar_conversion(
        ramp_input,
        physical_q8,
        cfg,
        chip_id,
        stream_id=7102,
        include_random_noise=False,
        stochastic_srm=False,
    )

    weights = {
        "NOMINAL": ideal_weight_q8(cfg),
        "CAL_CURRENT_MEAS": calibrated_current_q8,
        "CAL_NOISELESS_MEAS": calibrated_noiseless_q8,
        "ORACLE": physical_q8,
    }
    sine_codes: Dict[str, np.ndarray] = {}
    ramp_codes: Dict[str, np.ndarray] = {}
    saturation: Dict[str, float] = {}
    for name, weight_q8 in weights.items():
        sine_codes[name], sine_sat = rtl_reconstruct(
            sine_conversion.raw_bits,
            weight_q8,
            cfg,
            residue_q8=0,
        )
        ramp_codes[name], ramp_sat = rtl_reconstruct(
            ramp_conversion.raw_bits,
            weight_q8,
            cfg,
            residue_q8=0,
        )
        saturation[name] = max(sine_sat, ramp_sat)

    rows: List[Dict[str, object]] = []
    for name in DECODERS:
        dynamic = spectrum_metrics(sine_codes[name], cfg)
        static = linearity_metrics(ramp_codes[name], cfg)
        raw_rmse, aligned_rmse, aligned_max, code_gain = _affine_error(
            ramp_codes["ORACLE"],
            ramp_codes[name],
        )
        weight_rmse, weight_max = _weight_error(
            physical_q8,
            weights[name],
            cfg.frac_bits,
        )
        rows.append(
            {
                "chip_id": chip_id,
                "decoder": name,
                "sndr_db": dynamic["sndr_db"],
                "snr_db": dynamic["snr_db"],
                "sfdr_db": dynamic["sfdr_db"],
                "thd_db": dynamic["thd_db"],
                "enob": dynamic["enob"],
                "dnl_min_lsb": static["dnl_min_lsb"],
                "dnl_max_lsb": static["dnl_max_lsb"],
                "inl_min_lsb": static["inl_min_lsb"],
                "inl_max_lsb": static["inl_max_lsb"],
                "missing_codes": static["missing_codes"],
                "saturation_fraction": saturation[name],
                "code_rmse_to_oracle_raw_lsb": raw_rmse,
                "code_rmse_to_oracle_affine_lsb": aligned_rmse,
                "code_max_to_oracle_affine_lsb": aligned_max,
                "code_gain_to_oracle": code_gain,
                "weight_rmse_gain_aligned_lsb": weight_rmse,
                "weight_max_gain_aligned_lsb": weight_max,
            }
        )
    return rows


def summarize(values: Iterable[float]) -> Dict[str, float]:
    data = np.asarray(list(values), dtype=float)
    return {
        "mean": float(np.mean(data)),
        "std": float(np.std(data, ddof=1)) if data.size > 1 else 0.0,
        "min": float(np.min(data)),
        "p01": float(np.percentile(data, 1)),
        "p05": float(np.percentile(data, 5)),
        "median": float(np.percentile(data, 50)),
        "p95": float(np.percentile(data, 95)),
        "p99": float(np.percentile(data, 99)),
        "max": float(np.max(data)),
    }


def aggregate(rows: List[Dict[str, object]]) -> Dict[str, object]:
    metrics = [key for key in rows[0] if key not in {"chip_id", "decoder"}]
    return {
        decoder: {
            metric: summarize(float(row[metric]) for row in rows if row["decoder"] == decoder)
            for metric in metrics
        }
        for decoder in DECODERS
    }


def write_csv(rows: List[Dict[str, object]], path: Path) -> None:
    with path.open("w", newline="", encoding="utf-8") as handle:
        writer = csv.DictWriter(handle, fieldnames=list(rows[0]))
        writer.writeheader()
        writer.writerows(rows)


def plot_results(summary: Dict[str, object], outdir: Path) -> None:
    labels = ["Nominal", "Current cal", "Noiseless cal", "Oracle"]
    colors = ["#7a7a7a", "#167d95", "#1f9d55", "#6d5aa8"]

    fig, axes = plt.subplots(1, 3, figsize=(12.0, 4.1))
    for index, (axis, metric, title, unit) in enumerate((
        (axes[0], "sndr_db", "Noiseless dynamic SNDR", "dB"),
        (axes[1], "weight_rmse_gain_aligned_lsb", "Weight error", "LSB rms"),
        (axes[2], "code_rmse_to_oracle_affine_lsb", "Code error to oracle", "LSB rms"),
    )):
        medians = [float(summary[name][metric]["median"]) for name in DECODERS]
        p05 = [float(summary[name][metric]["p05"]) for name in DECODERS]
        p95 = [float(summary[name][metric]["p95"]) for name in DECODERS]
        display_medians = np.maximum(np.asarray(medians), 1e-4)
        display_p05 = np.maximum(np.asarray(p05), 1e-4)
        display_p95 = np.maximum(np.asarray(p95), display_medians)
        lower = display_medians - display_p05
        upper = display_p95 - display_medians
        bars = axis.bar(labels, display_medians, color=colors, width=0.66)
        axis.errorbar(
            labels,
            display_medians,
            yerr=np.vstack((lower, upper)),
            fmt="none",
            color="black",
            capsize=3,
        )
        if index > 0:
            axis.set_yscale("log")
        axis.bar_label(
            bars,
            labels=[f"{value:.3g}" if value > 0.0 else "0" for value in medians],
            padding=3,
            fontsize=8,
        )
        axis.set_title(title)
        axis.set_ylabel(unit)
        axis.grid(axis="y", alpha=0.25)
        axis.tick_params(axis="x", rotation=22)
    fig.suptitle("Mismatch-only validation, 512 chips, noiseless normal conversion")
    fig.tight_layout()
    fig.savefig(outdir / "fig_mismatch_only_summary.png", dpi=180)
    fig.savefig(outdir / "fig_mismatch_only_summary.pdf")
    plt.close(fig)


def run_campaign(cfg: FullSarConfig, outdir: Path, workers: int) -> Dict[str, object]:
    cfg.validate()
    outdir.mkdir(parents=True, exist_ok=True)
    rows: List[Dict[str, object]] = []
    with ProcessPoolExecutor(max_workers=workers) as executor:
        futures = {executor.submit(evaluate_chip, chip_id, cfg): chip_id for chip_id in range(cfg.n_chips)}
        for completed, future in enumerate(as_completed(futures), start=1):
            rows.extend(future.result())
            if completed % 16 == 0 or completed == cfg.n_chips:
                print(f"Completed {completed}/{cfg.n_chips} chips", flush=True)

    rows.sort(key=lambda row: (int(row["chip_id"]), DECODERS.index(str(row["decoder"]))))
    summary = aggregate(rows)
    write_csv(rows, outdir / "per_chip_metrics.csv")
    plot_results(summary, outdir)
    payload = {
        "status": "complete",
        "question": "Can foreground calibration remove static weight mismatch when normal conversion is noiseless?",
        "scope": (
            "Mismatch-only validation of the repository's abstract 20-decision normal-conversion path. "
            "All normal-conversion noise is disabled and SRM residue is excluded from decoding."
        ),
        "limitations": (
            "This does not yet model split-sampling/VCM/AZ/2-bit-flash timing or transistor-level charge redistribution."
        ),
        "config": asdict(cfg),
        "completed_chips": cfg.n_chips,
        "decoder_rows": len(rows),
        "summary": summary,
    }
    (outdir / "summary.json").write_text(json.dumps(payload, indent=2), encoding="utf-8")
    return payload


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--chips", type=int, default=512)
    parser.add_argument("--workers", type=int, default=max(1, min(8, (os.cpu_count() or 2) // 2)))
    parser.add_argument("--outdir", type=Path, default=DEFAULT_OUTDIR)
    return parser.parse_args()


def main() -> None:
    args = parse_args()
    cfg = noiseless_config(args.chips)
    payload = run_campaign(cfg, args.outdir, max(1, args.workers))
    print("\nMedian mismatch-only results")
    for decoder in DECODERS:
        metrics = payload["summary"][decoder]
        print(
            f"{decoder:20s} "
            f"SNDR={metrics['sndr_db']['median']:.3f} dB, "
            f"weight_RMSE={metrics['weight_rmse_gain_aligned_lsb']['median']:.4f} LSB, "
            f"code_RMSE={metrics['code_rmse_to_oracle_affine_lsb']['median']:.4f} LSB"
        )
    print(f"Artifacts: {args.outdir.resolve()}")


if __name__ == "__main__":
    main()
